{
 "title": "KrakenD",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count of completed requests, by HTTP method and response status in last min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_client_completed_count{http_client_method=\"GET\",http_client_status=\"200\"}[1m])",
     "legendFormat": "{{http_client_method}}-{{http_client_status}}"
    },
    {
     "expr": "rate(opencensus_io_http_client_completed_count{http_client_method=\"GET\",http_client_status=\"500\"}[1m])",
     "legendFormat": "{{http_client_method}}-{{http_client_status}}"
    }
   ]
  },
  {
   "title": "Server response count by status code in last min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_response_count_by_status_code{http_status=\"200\"}[1m])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(opencensus_io_http_server_response_count_by_status_code{http_status=\"500\"}[1m])",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Server request count by HTTP method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_request_count_by_method[5m])",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Latency distribution of HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "50 Quantile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "75 Quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "95 Quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(opencensus_io_http_server_latency_bucket[5m])) by (le))",
     "legendFormat": "99 Quantile"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Size distribution of HTTP request body",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_request_bytes_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Size distribution of HTTP response body (Last 5min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_response_bytes_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}